### ISSUE TITLE
Leader sequences

### ISSUE THREAD

**Issue by TCellTechie** [repseqio/library-imgt#7]
As someone has noted before, the leader sequences are missing from the library. You can find sequences that have both the leader and Vgene segments, under the header “"L-PART1+V-EXON" artificially spliced sets” on the following link: http://www.imgt.org/vquest/refseqh.html.

Constant regions can be found under the header “Constant gene artificially spliced exons sets”.

**Comment by dbolotin** [comment]
Hi,

sorry, we are not planing to invest additional major efforts into IMGT library port. The one we have so far already took too much work because of a very poor organization of IMGT's data (all the way from LIGMdb to the reference sequences for V-Quest). We might import C genes for popular species (I found that they are available at the links like http://www.imgt.org/genedb/GENElect?query=7.14+IGHC&species=Homo+sapiens), but I can't guarantee that.

We have a genome assembly based library that is built-in into MiXCR and available [here](https://github.com/repseqio/library) under CC license. If you have specific problems using the default library, and it can be fixed based on a high quality sequences form NCBI or other similar sources, we will be happy to address them and include the info into the library.
